# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/workspace/replace-parker/replace-23b

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/workspace/replace-parker/replace-23b

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/workspace/replace-parker/replace-23b/CMakeFiles /home/workspace/replace-parker/replace-23b//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/workspace/replace-parker/replace-23b/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named replace

# Build rule for target.
replace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 replace
.PHONY : replace

# fast build rule for target.
replace/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/build
.PHONY : replace/fast

src/23bParser.o: src/23bParser.cpp.o
.PHONY : src/23bParser.o

# target to build an object file
src/23bParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/23bParser.cpp.o
.PHONY : src/23bParser.cpp.o

src/23bParser.i: src/23bParser.cpp.i
.PHONY : src/23bParser.i

# target to preprocess a source file
src/23bParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/23bParser.cpp.i
.PHONY : src/23bParser.cpp.i

src/23bParser.s: src/23bParser.cpp.s
.PHONY : src/23bParser.s

# target to generate assembly for a file
src/23bParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/23bParser.cpp.s
.PHONY : src/23bParser.cpp.s

src/abacusLegalizer.o: src/abacusLegalizer.cpp.o
.PHONY : src/abacusLegalizer.o

# target to build an object file
src/abacusLegalizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/abacusLegalizer.cpp.o
.PHONY : src/abacusLegalizer.cpp.o

src/abacusLegalizer.i: src/abacusLegalizer.cpp.i
.PHONY : src/abacusLegalizer.i

# target to preprocess a source file
src/abacusLegalizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/abacusLegalizer.cpp.i
.PHONY : src/abacusLegalizer.cpp.i

src/abacusLegalizer.s: src/abacusLegalizer.cpp.s
.PHONY : src/abacusLegalizer.s

# target to generate assembly for a file
src/abacusLegalizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/abacusLegalizer.cpp.s
.PHONY : src/abacusLegalizer.cpp.s

src/abaxLegalizer.o: src/abaxLegalizer.cpp.o
.PHONY : src/abaxLegalizer.o

# target to build an object file
src/abaxLegalizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/abaxLegalizer.cpp.o
.PHONY : src/abaxLegalizer.cpp.o

src/abaxLegalizer.i: src/abaxLegalizer.cpp.i
.PHONY : src/abaxLegalizer.i

# target to preprocess a source file
src/abaxLegalizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/abaxLegalizer.cpp.i
.PHONY : src/abaxLegalizer.cpp.i

src/abaxLegalizer.s: src/abaxLegalizer.cpp.s
.PHONY : src/abaxLegalizer.s

# target to generate assembly for a file
src/abaxLegalizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/abaxLegalizer.cpp.s
.PHONY : src/abaxLegalizer.cpp.s

src/fft.o: src/fft.cpp.o
.PHONY : src/fft.o

# target to build an object file
src/fft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fft.cpp.o
.PHONY : src/fft.cpp.o

src/fft.i: src/fft.cpp.i
.PHONY : src/fft.i

# target to preprocess a source file
src/fft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fft.cpp.i
.PHONY : src/fft.cpp.i

src/fft.s: src/fft.cpp.s
.PHONY : src/fft.s

# target to generate assembly for a file
src/fft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fft.cpp.s
.PHONY : src/fft.cpp.s

src/fftsg.o: src/fftsg.cpp.o
.PHONY : src/fftsg.o

# target to build an object file
src/fftsg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg.cpp.o
.PHONY : src/fftsg.cpp.o

src/fftsg.i: src/fftsg.cpp.i
.PHONY : src/fftsg.i

# target to preprocess a source file
src/fftsg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg.cpp.i
.PHONY : src/fftsg.cpp.i

src/fftsg.s: src/fftsg.cpp.s
.PHONY : src/fftsg.s

# target to generate assembly for a file
src/fftsg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg.cpp.s
.PHONY : src/fftsg.cpp.s

src/fftsg2d.o: src/fftsg2d.cpp.o
.PHONY : src/fftsg2d.o

# target to build an object file
src/fftsg2d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg2d.cpp.o
.PHONY : src/fftsg2d.cpp.o

src/fftsg2d.i: src/fftsg2d.cpp.i
.PHONY : src/fftsg2d.i

# target to preprocess a source file
src/fftsg2d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg2d.cpp.i
.PHONY : src/fftsg2d.cpp.i

src/fftsg2d.s: src/fftsg2d.cpp.s
.PHONY : src/fftsg2d.s

# target to generate assembly for a file
src/fftsg2d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg2d.cpp.s
.PHONY : src/fftsg2d.cpp.s

src/fftsg3d.o: src/fftsg3d.cpp.o
.PHONY : src/fftsg3d.o

# target to build an object file
src/fftsg3d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg3d.cpp.o
.PHONY : src/fftsg3d.cpp.o

src/fftsg3d.i: src/fftsg3d.cpp.i
.PHONY : src/fftsg3d.i

# target to preprocess a source file
src/fftsg3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg3d.cpp.i
.PHONY : src/fftsg3d.cpp.i

src/fftsg3d.s: src/fftsg3d.cpp.s
.PHONY : src/fftsg3d.s

# target to generate assembly for a file
src/fftsg3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/fftsg3d.cpp.s
.PHONY : src/fftsg3d.cpp.s

src/initialPlace.o: src/initialPlace.cpp.o
.PHONY : src/initialPlace.o

# target to build an object file
src/initialPlace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/initialPlace.cpp.o
.PHONY : src/initialPlace.cpp.o

src/initialPlace.i: src/initialPlace.cpp.i
.PHONY : src/initialPlace.i

# target to preprocess a source file
src/initialPlace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/initialPlace.cpp.i
.PHONY : src/initialPlace.cpp.i

src/initialPlace.s: src/initialPlace.cpp.s
.PHONY : src/initialPlace.s

# target to generate assembly for a file
src/initialPlace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/initialPlace.cpp.s
.PHONY : src/initialPlace.cpp.s

src/log.o: src/log.cpp.o
.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/macroLegalizer.o: src/macroLegalizer.cpp.o
.PHONY : src/macroLegalizer.o

# target to build an object file
src/macroLegalizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/macroLegalizer.cpp.o
.PHONY : src/macroLegalizer.cpp.o

src/macroLegalizer.i: src/macroLegalizer.cpp.i
.PHONY : src/macroLegalizer.i

# target to preprocess a source file
src/macroLegalizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/macroLegalizer.cpp.i
.PHONY : src/macroLegalizer.cpp.i

src/macroLegalizer.s: src/macroLegalizer.cpp.s
.PHONY : src/macroLegalizer.s

# target to generate assembly for a file
src/macroLegalizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/macroLegalizer.cpp.s
.PHONY : src/macroLegalizer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nesterovBase.o: src/nesterovBase.cpp.o
.PHONY : src/nesterovBase.o

# target to build an object file
src/nesterovBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/nesterovBase.cpp.o
.PHONY : src/nesterovBase.cpp.o

src/nesterovBase.i: src/nesterovBase.cpp.i
.PHONY : src/nesterovBase.i

# target to preprocess a source file
src/nesterovBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/nesterovBase.cpp.i
.PHONY : src/nesterovBase.cpp.i

src/nesterovBase.s: src/nesterovBase.cpp.s
.PHONY : src/nesterovBase.s

# target to generate assembly for a file
src/nesterovBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/nesterovBase.cpp.s
.PHONY : src/nesterovBase.cpp.s

src/nesterovPlace.o: src/nesterovPlace.cpp.o
.PHONY : src/nesterovPlace.o

# target to build an object file
src/nesterovPlace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/nesterovPlace.cpp.o
.PHONY : src/nesterovPlace.cpp.o

src/nesterovPlace.i: src/nesterovPlace.cpp.i
.PHONY : src/nesterovPlace.i

# target to preprocess a source file
src/nesterovPlace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/nesterovPlace.cpp.i
.PHONY : src/nesterovPlace.cpp.i

src/nesterovPlace.s: src/nesterovPlace.cpp.s
.PHONY : src/nesterovPlace.s

# target to generate assembly for a file
src/nesterovPlace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/nesterovPlace.cpp.s
.PHONY : src/nesterovPlace.cpp.s

src/outputWriter.o: src/outputWriter.cpp.o
.PHONY : src/outputWriter.o

# target to build an object file
src/outputWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/outputWriter.cpp.o
.PHONY : src/outputWriter.cpp.o

src/outputWriter.i: src/outputWriter.cpp.i
.PHONY : src/outputWriter.i

# target to preprocess a source file
src/outputWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/outputWriter.cpp.i
.PHONY : src/outputWriter.cpp.i

src/outputWriter.s: src/outputWriter.cpp.s
.PHONY : src/outputWriter.s

# target to generate assembly for a file
src/outputWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/outputWriter.cpp.s
.PHONY : src/outputWriter.cpp.s

src/partitioner.o: src/partitioner.cpp.o
.PHONY : src/partitioner.o

# target to build an object file
src/partitioner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/partitioner.cpp.o
.PHONY : src/partitioner.cpp.o

src/partitioner.i: src/partitioner.cpp.i
.PHONY : src/partitioner.i

# target to preprocess a source file
src/partitioner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/partitioner.cpp.i
.PHONY : src/partitioner.cpp.i

src/partitioner.s: src/partitioner.cpp.s
.PHONY : src/partitioner.s

# target to generate assembly for a file
src/partitioner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/partitioner.cpp.s
.PHONY : src/partitioner.cpp.s

src/placerBase.o: src/placerBase.cpp.o
.PHONY : src/placerBase.o

# target to build an object file
src/placerBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/placerBase.cpp.o
.PHONY : src/placerBase.cpp.o

src/placerBase.i: src/placerBase.cpp.i
.PHONY : src/placerBase.i

# target to preprocess a source file
src/placerBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/placerBase.cpp.i
.PHONY : src/placerBase.cpp.i

src/placerBase.s: src/placerBase.cpp.s
.PHONY : src/placerBase.s

# target to generate assembly for a file
src/placerBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/placerBase.cpp.s
.PHONY : src/placerBase.cpp.s

src/plot.o: src/plot.cpp.o
.PHONY : src/plot.o

# target to build an object file
src/plot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/plot.cpp.o
.PHONY : src/plot.cpp.o

src/plot.i: src/plot.cpp.i
.PHONY : src/plot.i

# target to preprocess a source file
src/plot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/plot.cpp.i
.PHONY : src/plot.cpp.i

src/plot.s: src/plot.cpp.s
.PHONY : src/plot.s

# target to generate assembly for a file
src/plot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/plot.cpp.s
.PHONY : src/plot.cpp.s

src/replace.o: src/replace.cpp.o
.PHONY : src/replace.o

# target to build an object file
src/replace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/replace.cpp.o
.PHONY : src/replace.cpp.o

src/replace.i: src/replace.cpp.i
.PHONY : src/replace.i

# target to preprocess a source file
src/replace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/replace.cpp.i
.PHONY : src/replace.cpp.i

src/replace.s: src/replace.cpp.s
.PHONY : src/replace.s

# target to generate assembly for a file
src/replace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/replace.cpp.s
.PHONY : src/replace.cpp.s

src/technology.o: src/technology.cpp.o
.PHONY : src/technology.o

# target to build an object file
src/technology.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/technology.cpp.o
.PHONY : src/technology.cpp.o

src/technology.i: src/technology.cpp.i
.PHONY : src/technology.i

# target to preprocess a source file
src/technology.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/technology.cpp.i
.PHONY : src/technology.cpp.i

src/technology.s: src/technology.cpp.s
.PHONY : src/technology.s

# target to generate assembly for a file
src/technology.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/technology.cpp.s
.PHONY : src/technology.cpp.s

src/terminalModifier.o: src/terminalModifier.cpp.o
.PHONY : src/terminalModifier.o

# target to build an object file
src/terminalModifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/terminalModifier.cpp.o
.PHONY : src/terminalModifier.cpp.o

src/terminalModifier.i: src/terminalModifier.cpp.i
.PHONY : src/terminalModifier.i

# target to preprocess a source file
src/terminalModifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/terminalModifier.cpp.i
.PHONY : src/terminalModifier.cpp.i

src/terminalModifier.s: src/terminalModifier.cpp.s
.PHONY : src/terminalModifier.s

# target to generate assembly for a file
src/terminalModifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replace.dir/build.make CMakeFiles/replace.dir/src/terminalModifier.cpp.s
.PHONY : src/terminalModifier.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... replace"
	@echo "... src/23bParser.o"
	@echo "... src/23bParser.i"
	@echo "... src/23bParser.s"
	@echo "... src/abacusLegalizer.o"
	@echo "... src/abacusLegalizer.i"
	@echo "... src/abacusLegalizer.s"
	@echo "... src/abaxLegalizer.o"
	@echo "... src/abaxLegalizer.i"
	@echo "... src/abaxLegalizer.s"
	@echo "... src/fft.o"
	@echo "... src/fft.i"
	@echo "... src/fft.s"
	@echo "... src/fftsg.o"
	@echo "... src/fftsg.i"
	@echo "... src/fftsg.s"
	@echo "... src/fftsg2d.o"
	@echo "... src/fftsg2d.i"
	@echo "... src/fftsg2d.s"
	@echo "... src/fftsg3d.o"
	@echo "... src/fftsg3d.i"
	@echo "... src/fftsg3d.s"
	@echo "... src/initialPlace.o"
	@echo "... src/initialPlace.i"
	@echo "... src/initialPlace.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/macroLegalizer.o"
	@echo "... src/macroLegalizer.i"
	@echo "... src/macroLegalizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nesterovBase.o"
	@echo "... src/nesterovBase.i"
	@echo "... src/nesterovBase.s"
	@echo "... src/nesterovPlace.o"
	@echo "... src/nesterovPlace.i"
	@echo "... src/nesterovPlace.s"
	@echo "... src/outputWriter.o"
	@echo "... src/outputWriter.i"
	@echo "... src/outputWriter.s"
	@echo "... src/partitioner.o"
	@echo "... src/partitioner.i"
	@echo "... src/partitioner.s"
	@echo "... src/placerBase.o"
	@echo "... src/placerBase.i"
	@echo "... src/placerBase.s"
	@echo "... src/plot.o"
	@echo "... src/plot.i"
	@echo "... src/plot.s"
	@echo "... src/replace.o"
	@echo "... src/replace.i"
	@echo "... src/replace.s"
	@echo "... src/technology.o"
	@echo "... src/technology.i"
	@echo "... src/technology.s"
	@echo "... src/terminalModifier.o"
	@echo "... src/terminalModifier.i"
	@echo "... src/terminalModifier.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

